# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status'),
        ),
    ]
