# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('name', models.CharField(blank=True, default=None, help_text='Leave this field blank, a name will be generated automatically', max_length=255, verbose_name='Icon name')),
                ('icons', models.CharField(choices=[('google-plus', 'google-plus'), ('google-wallet', 'google-wallet'), ('pinterest', 'pinterest'), ('facebook', 'facebook'), ('odnoklassniki', 'odnoklassniki'), ('telegram', 'telegram'), ('twitter', 'twitter'), ('skype', 'skype'), ('tumblr', 'tumblr'), ('youtube', 'youtube'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('vimeo', 'vimeo'), ('vk', 'vk'), ('booking', 'booking'), ('tripadvisor', 'tripadvisor')], help_text='Select an icon from the list', max_length=255, verbose_name='Select icon')),
                ('url', models.CharField(blank=True, default=None, help_text='If you want that icon was a link to enter the website address', max_length=255, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.CreateModel(
            name='IconGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Group name')),
                ('icons', models.ManyToManyField(to='icons.Icon', verbose_name='Select icons')),
            ],
            options={
                'verbose_name': 'Group icons',
                'verbose_name_plural': 'Group icons',
            },
        ),
    ]
