# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0003_auto_20170612_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icongroup',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Alias'),
        ),
    ]
