# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0005_auto_20170721_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icons',
            field=models.CharField(choices=[('google-plus', 'google-plus'), ('google-wallet', 'google-wallet'), ('pinterest', 'pinterest'), ('facebook', 'facebook'), ('odnoklassniki', 'odnoklassniki'), ('telegram', 'telegram'), ('twitter', 'twitter'), ('skype', 'skype'), ('tumblr', 'tumblr'), ('youtube', 'youtube'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('vimeo', 'vimeo'), ('vk', 'vk'), ('booking', 'booking'), ('tripadvisor', 'tripadvisor'), ('book', 'book'), ('clear-sun', 'samopoznanie')], help_text='Select an icon from the list', max_length=255, verbose_name='Select icon'),
        ),
    ]
