# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icons', '0004_auto_20170612_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create date')),
                ('show_date', models.BooleanField(default=True, verbose_name='Show create date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alias')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('image', models.ImageField(blank=True, help_text='Main picture of the news (optional field). This picture will by displayed in the news list', null=True, upload_to='news_images/', verbose_name='Image')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('icons_group', models.ForeignKey(blank=True, help_text='If groups of icons are not created then create them', null=True, on_delete=django.db.models.deletion.CASCADE, to='icons.IconGroup', verbose_name='Select group icons')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News list',
            },
        ),
    ]
