# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='Show image?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Main picture of the news (optional field). This picture will by displayed in the news list', null=True, upload_to='news_images/', verbose_name='Image'),
        ),
    ]
