# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(help_text='Add photo to the photo gallery', upload_to='photo_gallery/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('alias', models.CharField(max_length=255, verbose_name='Alias')),
            ],
            options={
                'verbose_name': 'Photo gallery',
                'verbose_name_plural': 'Photo galleries',
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGalleryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('video_code', models.CharField(blank=True, help_text="Paste in this field youtube video's code. For example: https://youtu.be/<strong>ZiC8ZSKKXwU</strong>", max_length=255, null=True, verbose_name='Video code')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.VideoGallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoGallery'),
        ),
    ]
