# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='alias',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alias'),
        ),
    ]
