# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_photo_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
    ]
