# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Alias')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Main picture of the Team (optional field)', upload_to='team/', verbose_name='Image')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
