# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 03:04
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='Main picture of the Team (optional field)', upload_to='team/', verbose_name='Image'),
        ),
    ]
