# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20170621_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='show_image',
            field=models.BooleanField(default=True, editable=False, verbose_name='Show image?'),
        ),
    ]
