# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_member_show_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Main picture of the Team (optional field)', null=True, upload_to='team/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='Show image?'),
        ),
    ]
