# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255, verbose_name='Copyright text')),
            ],
            options={
                'verbose_name': 'Copyright',
            },
        ),
        migrations.CreateModel(
            name='ListIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListIconsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('icon', models.CharField(blank=True, choices=[('lotos', 'Lotos'), ('om-symbol', 'Om symbol'), ('skype', 'Skype'), ('views', 'Views'), ('cube-questions-mark', 'Cube questions'), ('moon', 'Moon')], max_length=20, verbose_name='Icon')),
                ('color', models.CharField(blank=True, choices=[('#F8F8F8', 'gray-light'), ('#898989', 'gray'), ('#70C051', 'green'), ('#FFC859', 'yellow'), ('#F26829', 'orange'), ('#C1E0FF', 'blue ')], max_length=20, verbose_name='Header color')),
                ('text', models.TextField(max_length=255, verbose_name='Text')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singletons.ListIcons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YogaAlliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('url', models.CharField(blank=True, help_text='Add the url of the page if you want that the text field was a link', max_length=255, null=True, verbose_name='Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YogaAllianceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yoga_alliance/', verbose_name='Image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singletons.YogaAlliance')),
            ],
        ),
    ]
