# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletons', '0003_auto_20170613_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodsimages',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image alternative text'),
        ),
    ]
