# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0006_auto_20170721_1217'),
        ('singletons', '0004_paymentmethodsimages_image_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatIconBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons_group', models.ForeignKey(blank=True, help_text='If groups of icons are not created then create them', null=True, on_delete=django.db.models.deletion.CASCADE, to='icons.IconGroup', verbose_name='Select group icons')),
            ],
            options={
                'verbose_name': 'Icons float block',
            },
        ),
    ]
