# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singletons', '0005_floaticonblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floaticonblock',
            options={'verbose_name': 'Float icons block'},
        ),
    ]
