# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icons', '0004_auto_20170612_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Create date')),
                ('show_date', models.BooleanField(default=True, verbose_name='Show create date')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('alias', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, help_text='Main picture of the article (optional field)', upload_to='articles/', verbose_name='Image')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('icons_group', models.ForeignKey(blank=True, default=None, help_text='If groups of icons are not created then create them', on_delete=django.db.models.deletion.CASCADE, to='icons.IconGroup', verbose_name='Select group icons')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
