# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170613_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icons_group',
            field=models.ForeignKey(blank=True, help_text='If groups of icons are not created then create them', on_delete=django.db.models.deletion.CASCADE, to='icons.IconGroup', verbose_name='Select group icons'),
        ),
    ]
