# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170613_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date'),
        ),
    ]
