# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20170621_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='Show image?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_date',
            field=models.BooleanField(default=True, verbose_name='Show create date?'),
        ),
    ]
