# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20170621_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished')], default='u', help_text='Select a status publish.', max_length=1, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Alias')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(help_text='Main picture of the article (optional field)', upload_to='articles/', verbose_name='Image')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.CategoryArticle', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.CategoryArticle', verbose_name='Category'),
        ),
    ]
