# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20170715_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Keywords are written comma-separated, for example "word 1, word 2, word 3, ..."', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='categoryarticle',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Keywords are written comma-separated, for example "word 1, word 2, word 3, ..."', verbose_name='Keywords'),
        ),
    ]
