# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20170813_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_homepage',
            field=models.BooleanField(default=False, help_text='only one article can be displayed on the main page. If the checkbox is already installed on another article, the new checkbox will replace it.', verbose_name='Show in index page?'),
        ),
    ]
