# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_auto_20170715_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='meta_title',
        ),
    ]
