# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 21:43
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20170608_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='slider', verbose_name='Image'),
        ),
    ]
