# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icons', '0004_auto_20170612_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Contacts', max_length=255, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number first')),
                ('phone_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number second')),
                ('icons_group', models.ForeignKey(blank=True, help_text='If groups of icons are not created then create them', null=True, on_delete=django.db.models.deletion.CASCADE, to='icons.IconGroup', verbose_name='Select group icons')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
