# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0008_bookingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalleriesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Keywords are written comma-separated, for example "word 1, word 2, word 3, ..."', verbose_name='Keywords')),
            ],
            options={
                'abstract': False,
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
