# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0009_photogalleriespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='members',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='photogalleriespage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='testimonialspage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='If this field is empty, it dublicate Article Title.', max_length=255, verbose_name='Title'),
        ),
    ]
