# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='resources.BookCategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Main picture of the Book (optional field)', null=True, upload_to='books/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Book title'),
        ),
    ]
