# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170716_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image alternative text'),
        ),
    ]
